import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import SideBar from "@/components/SideBar";
import "./globals.css";
import ClientLayout from '@/components/ClientLayout';


const montserrat = Montserrat({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Scribba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <ClientLayout>
        {children}
        </ClientLayout>
      </body>
    </html>
  );
}
